<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "dkd_redis_sessions"
 *
 * Auto generated by Extension Builder 2013-08-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Redis Session Storage',
	'description' => 'Session Storage service that uses Redis as storage backend',
	'category' => 'services',
	'author' => 'Thorsten Kahler',
	'author_email' => 'thorsten.kahler@dkd.de',
	'author_company' => 'dkd Internet Service GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.2-6.2.99',
			'fluid' => '6.2-6.2.99',
			'typo3' => '6.2-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>